global:
  scrape_interval: 5s         # Частота сбора метрики
  evaluation_interval: 5s     # Частота проверки правил алертов

rule_files:
  - "alerts.yaml"

scrape_configs:
  - job_name: "ml_service"
    static_configs:
      - targets: ["host.docker.internal:8000"]
